get   "/",            forward: "/index.groovy"
get   "/feed",        forward: "/feed.groovy"
post  "/feed",        forward: "/post.groovy"
post  "/comment",     forward: "/comment.groovy"
post  "/invite",      forward: "/invite.groovy"
get   "/join/@userid",forward: "/join.groovy?id=@userid"
get   "/friends",     forward: "/friends.groovy"
